
  name: ort
  version: '0.1'
  summary: Polish ortography tutor
  description: |
    This software helps you learn polish ortography rules.

  grade: devel
  confinement: devmode

  parts:
    my-part:
      plugin: nil
